version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: arag-backend-prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - DEBUG=false
    env_file:
      - ./backend/.env.prod
    volumes:
      - backend_data:/app/data
    networks:
      - arag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arag-frontend-prod
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - backend
    networks:
      - arag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  arag-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
